### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by PhillipUg**

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @PhillipUg and @teekaytech 

### Good job so far :clap: on your first project. However, you have a few changes you need to work on.
- Write a descriptive pull request, follow this [guide](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) for reference
- The page goes full-width, don't limit it to the middle
width
- Rebuilt the user details section
description
- This is expected
expcted
- Add a few comments to your featured video
comments
- Validate your code with this [online tool](https://validator.w3.org/#validate_by_upload)
validate

### Make these changes and resubmit for another review
- For assistance contact me on @rOluochKe

**Comment by PhillipUg** [comment]
## Fixes
  * Added a descriptive pull request
  * Expanded web page to full width
  * Rebuilt User details section
  * Added few comments to the featured video
  * Validated code with W3C Online tool
  * Other minor improvements to the general page outlook

**Review by euqueme — CHANGES_REQUESTED** [review]
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @PhillipUg and @teekaytech :balloon: :lollipop: 

### Thank you for doing all the changes required by the previous reviewer :medal_sports:  your project is looking better and better every time :art: :eyes: 

### I have 2 follow up changes for you to make and an optional one :point_down: 

## Video

- [ ] the previous reviewer asked you to fill 100% of the page  and you did it, but now you have too much space between the video and the sidebar, so please check out the original page and see that the video actually has to be bigger in size

- Yours

image

- Original

image

## General

- [ ] please fix all the errors and warnings found by the [HTML validator,](https://validator.w3.org/#validate_by_upload) we cannot approve any project that has HTML errors

image

## Navbar

- [ ] [OPTIONAL] this wasn't pointed out before but the icons at the right of the navbar should have less space between them, also the search bar is in the center of the page look at the original

- Yours

image

- Original

image

### That's it, team! :raised_hands:  

### Please :pray: fix do the changes :memo: and submit back for a code review when you are done :rocket: 

Happy coding! :woman_technologist: 

PROJECT STATUS : REQUESTED CHANGES :traffic_light:

**Comment by PhillipUg** [comment]
We realized that we had forgotten to push the changes we had made to our remote repository. Here is how our page looks like on our machines now.
<br>

screen2




* In addition, our code has also passed all validation

**Comment by majovanilla** [comment]
Hey @PhillipUg and @teekaytech , 👋

## You did an *amazing*🌟 ✨ job working on this project! 👊🏻  💯
The effort was worth it!!

Your second PR message was so much better. Keep it up!

**Your project has been approved**

You can merge and submit the project completion form-


Happy coding 🤓

--Maria Reyes



You can find me on Social Media below 👇 . Remember to say hi!

[GitHub](https://github.com/majovanilla) [Twitter](https://twitter.com/MajoVanilla) [LinkedIn](https://www.linkedin.com/in/majoreyesparroquin/)

**Pull request merged**
